import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../components/navbar/Navbar'
import Footer from '../components/footer/Footer'
import Provider from '../SessionProvider'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'StorySailor',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
         <head>
          <link rel="shortcut icon" href="/2.png" />
      </head>
      <body className={inter.className}>
       <Provider>     
          <Navbar />
          {children}
          <Footer />
        </Provider>

      {/* <Footer/> */}
      </body>
    </html>
  )
}
